apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.spValidator.name }}
  labels:
    {{- include "linkerd-certs.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.spValidator.secretName }}
  duration: {{ .Values.spValidator.duration }}
  renewBefore: {{ .Values.spValidator.renewBefore }}
  issuerRef:
    name: {{ .Values.webhook.name }}
    kind: Issuer
  commonName: {{ .Values.spValidator.commonName }}
  dnsNames:
    {{- append .Values.spValidator.extraDnsNames .Values.spValidator.commonName | toYaml | nindent 4 }}
  {{- .Values.stdCertConfig | toYaml | nindent 2 }}
