# Default values for linkerd-certs.
nameOverride: ""
fullnameOverride: ""

# clusterResourceNamespace defines where Cert Manager looks for ClusterIssuer secrets
clusterResourceNamespace: cert-manager

selfsignedIssuer:
  name: linkerd-selfsigned

controlPlane:
  trustAnchor:
    name: linkerd-trust-anchor
    commonName: root.linkerd.cluster.local
    secretName: linkerd-trust-anchor

  identity:
    name: linkerd-identity
    commonName: identity.linkerd.cluster.local
    secretName: linkerd-identity

webhook:
  issuer:
    name: linkerd-webhook-trust-anchor
    commonName: webhook.linkerd.cluster.local
    secretName: linkerd-webhook-trust-anchor

  certs:
    policyValidator:
      name: linkerd-policy-validator
      encoding: PKCS8

    proxyInjector:
      name: linkerd-proxy-injector

    spValidator:
      name: linkerd-sp-validator

    jaegerInjector:
      name: jaeger-injector
      namespace: linkerd-jaeger

    vizTap:
      name: tap
      namespace: linkerd-viz

    vizTapInjector:
      name: tap-injector
      namespace: linkerd-viz
